// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHVCZ0eKnkRawFm5j-wfD80N21bDt0GEU',
    appId: '1:992981778702:web:d66e850f9e460cb5aa175f',
    messagingSenderId: '992981778702',
    projectId: 'fir-auth-18-3c13e',
    authDomain: 'fir-auth-18-3c13e.firebaseapp.com',
    storageBucket: 'fir-auth-18-3c13e.appspot.com',
    measurementId: 'G-8289DSYKSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUfTjVN15tqAzuP3MLNJGIqrBbld1nw8k',
    appId: '1:992981778702:android:9eeee10985069fc2aa175f',
    messagingSenderId: '992981778702',
    projectId: 'fir-auth-18-3c13e',
    storageBucket: 'fir-auth-18-3c13e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbaOl_EVpykE-HlDKkEvU-Whp2zJTUG-M',
    appId: '1:992981778702:ios:d64c1b614a5574bcaa175f',
    messagingSenderId: '992981778702',
    projectId: 'fir-auth-18-3c13e',
    storageBucket: 'fir-auth-18-3c13e.appspot.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbaOl_EVpykE-HlDKkEvU-Whp2zJTUG-M',
    appId: '1:992981778702:ios:d64c1b614a5574bcaa175f',
    messagingSenderId: '992981778702',
    projectId: 'fir-auth-18-3c13e',
    storageBucket: 'fir-auth-18-3c13e.appspot.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHVCZ0eKnkRawFm5j-wfD80N21bDt0GEU',
    appId: '1:992981778702:web:1c81001be5875980aa175f',
    messagingSenderId: '992981778702',
    projectId: 'fir-auth-18-3c13e',
    authDomain: 'fir-auth-18-3c13e.firebaseapp.com',
    storageBucket: 'fir-auth-18-3c13e.appspot.com',
    measurementId: 'G-CLV7L1K3J7',
  );
}
