// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtC1zKVZBCFFU9I_xLSzaN4lw7vE9ZrY0',
    appId: '1:691467883496:web:5242d88bb01449c9d54a5d',
    messagingSenderId: '691467883496',
    projectId: 'flutter-firebase-example-c27f5',
    authDomain: 'flutter-firebase-example-c27f5.firebaseapp.com',
    storageBucket: 'flutter-firebase-example-c27f5.appspot.com',
    measurementId: 'G-WJEKZ12B6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDduulONgddZ1rrm_l2_Utq1BYPVJs7iJM',
    appId: '1:691467883496:android:6784debfff168be9d54a5d',
    messagingSenderId: '691467883496',
    projectId: 'flutter-firebase-example-c27f5',
    storageBucket: 'flutter-firebase-example-c27f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD5UcvKsdMYTJWacPa2GAd-CwVNY5zHOQ',
    appId: '1:691467883496:ios:4a1ba0845fd1052ed54a5d',
    messagingSenderId: '691467883496',
    projectId: 'flutter-firebase-example-c27f5',
    storageBucket: 'flutter-firebase-example-c27f5.appspot.com',
    iosBundleId: 'com.example.firebase1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD5UcvKsdMYTJWacPa2GAd-CwVNY5zHOQ',
    appId: '1:691467883496:ios:4a1ba0845fd1052ed54a5d',
    messagingSenderId: '691467883496',
    projectId: 'flutter-firebase-example-c27f5',
    storageBucket: 'flutter-firebase-example-c27f5.appspot.com',
    iosBundleId: 'com.example.firebase1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtC1zKVZBCFFU9I_xLSzaN4lw7vE9ZrY0',
    appId: '1:691467883496:web:e9f66f5c2656d75ad54a5d',
    messagingSenderId: '691467883496',
    projectId: 'flutter-firebase-example-c27f5',
    authDomain: 'flutter-firebase-example-c27f5.firebaseapp.com',
    storageBucket: 'flutter-firebase-example-c27f5.appspot.com',
    measurementId: 'G-2XYGLMHLJD',
  );
}
